### ISSUE TITLE
Show logs after a day...

### ISSUE THREAD

**Issue by cjskw** [fpillet/NSLogger#216]
Yesterday i use simulater to test logger, but the NSLogger App didn't show up every time.Today it shows up and display messages from yesterday...

**Comment by fpillet** [comment]
Wow that's ... interesting. I've noticed some weird issues lately, but never that bad. I'm still running 10.11 though, are you seeing this with Sierra?

**Comment by cjskw** [comment]
I'm running 10.11 too.

**Comment by fpillet** [comment]
Ok thanks for the clarification. I have no explanation to give for this issue atm -- this is another weirdness with Bonjour running in the simulator! What if you configure the logger in the app with the fixed local IP address of your Mac?

**Comment by cjskw** [comment]
Maybe this info can help, the NSLogger Viewer didn't shows up correctly when i set system http&https proxy,but when i clear the proxy setting everythin back to normal.

**Comment by MonsieurDart** [comment]
Try using configuring the logger client app (iOS) to log to localhost (or to your machine IP address):

        LoggerSetViewerHost(nil, "localhost" as NSString, 50000)

Then configure the viewer macOS app to listen to TCP, on port 50000. This is done from the "Preferences" pane of NSLogger.app.

If your problem is the same as mine, it might be related to a possible bug in the NSLogger SSL configuration (we are working on it).

**Comment by fpillet** [comment]
This issue is fixed in 1.8.0. You can verify it by using HEAD instead of stock 1.7. Release is imminent.
